networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress_website:
    driver: local
    driver_opts:
      type: none
      o: bind
# TODO: Replace path with /home/ejakob/data as required by the subject
      device: /Users/eliasjakob/inception_data/wordpress/
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
# TODO: Replace path with /home/ejakob/data as required by the subject
      device: /Users/eliasjakob/inception_data/mariadb/

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_password_ad:
    file: ../secrets/wp_password_ad.txt

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_website:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_website:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - wp_password
      - wp_password_ad
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
