networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress_website:
  mariadb_data:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_website:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_website:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
